# Generated by Django 3.2.9 on 2021-11-19 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rental_charge', models.PositiveSmallIntegerField()),
                ('additional_charge', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'charges',
            },
        ),
    ]
