# Generated by Django 3.2.9 on 2021-11-19 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rental_charge', models.PositiveSmallIntegerField()),
                ('additional_charge', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'charges',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='DiscountOrPenalties',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=32)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charges.type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charges.unit')),
            ],
            options={
                'db_table': 'discount_or_penalties',
            },
        ),
    ]
