# Generated by Django 3.2.9 on 2021-11-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_discountorpenalties_type_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountorpenalties',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
