# Generated by Django 3.2.9 on 2021-11-19 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('border_coords', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charges.charge')),
            ],
            options={
                'db_table': 'service_areas',
            },
        ),
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.FloatField()),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.servicearea')),
            ],
            options={
                'db_table': 'parking_areas',
            },
        ),
        migrations.CreateModel(
            name='ForbiddenArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('border_coords', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.servicearea')),
            ],
            options={
                'db_table': 'forbidden_areas',
            },
        ),
    ]
