# Generated by Django 3.2.9 on 2021-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_discountorpenalties_type_unit'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='discount_or_penalties',
            field=models.ManyToManyField(related_name='service_areas', to='charges.DiscountOrPenalties'),
        ),
    ]
